/* Auto generated file by build command shell.
    !!!!!!!! Do not edit this file. !!!!!!!!
    Created time : Mon Jan 14 15:54:51 KST 2013
    Created by chero@pantech.com (GS1 Team)
*/
#ifndef BOARD_REV_H
#define BOARD_REV_H

/*
Current MODEL ID is T_MAGNUS 
LINUX Kernel Define & macro function is as follows
#define CONFIG_MACH_MSM8960_MAGNUS
machine_is_msm8960_magnus() function
*/

#define WS10  0x01
#define WS20  0x02
#define TP10  0x04
#define TP20  0x08
#define TP30  0x10

#define BOARD_VER   TP30
#endif /*BOARD_REV_H*/
