
# Makefile for WCNSS triple-play driver, 20120726 thkim_wifi the patch to prevent memory fragmentation when the wlan host driver loads.(Case Number: 00924847)

wcnsscore-objs += wcnss_wlan.o wcnss_riva.o qcomwlan_secif.o wcnss_prealloc.o

obj-$(CONFIG_WCNSS_CORE) += wcnsscore.o
